name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.set_image_url.outputs.image_url }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        set-timestamps: true  #

    - name: Set image url
      id: set_image_url
      run: | 
        URL="ghcr.io/${{ github.repository }}:v1.0.${{(github.run_number)}}-${{github.sha}}"
        echo "IMAGE_URL=$URL" >> $GITHUB_ENV
        echo "image_url=$URL" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./jupyter.Dockerfile
        push: true
        tags: ${{ env.IMAGE_URL }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy_pipeline:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Εγκατάσταση του yq στον runner
      - name: Install yq
        uses: mikefarah/yq@v4.44.1
        with:
          cmd: yq --version

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Εκτέλεση του deployment με το σωστό mount για το yq
      - name: Detect and Submit Changed Pipelines
        env:
          IMAGE_URL: ${{ needs.build_and_push.outputs.image_url }}
          KUBEFLOW_URL: ${{ secrets.KUBEFLOW_URL }}
          PRE_COMMIT_SHA: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          KUBEFLOW_USERNAME: ${{ secrets.KUBEFLOW_USERNAME }}
          KUBEFLOW_PASSWORD: ${{ secrets.KUBEFLOW_PASSWORD }}
        run: |
          YQ_PATH=$(which yq)
          docker run --rm \
            --entrypoint /bin/bash \
            -v $(pwd)/.git:/home/jovyan/.git \
            -v $YQ_PATH:/usr/bin/yq \
            -e PRE_COMMIT_SHA -e SHA \
            -e KUBEFLOW_URL -e KUBEFLOW_USERNAME -e KUBEFLOW_PASSWORD \
            -e IMAGE_URL \
            ${{ needs.build_and_push.outputs.image_url }} \
            -c "git config --global --add safe.directory /home/jovyan && chmod +x scripts/deploy_pipeline.sh && ./scripts/deploy_pipeline.sh"