name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.set_image_url.outputs.image_url }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set image url
      id: set_image_url
      run: | 
        URL="ghcr.io/${{ github.repository }}:v1.0.${{(github.run_number)}}-${{github.sha}}"
        echo "IMAGE_URL=$URL" >> $GITHUB_ENV
        echo "image_url=$URL" >> $GITHUB_OUTPUT

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./jupyter.Dockerfile
        push: true
        tags: ${{ env.IMAGE_URL }}

  deploy_pipeline:
    needs: build_and_push
    runs-on: ubuntu-latest
    outputs:
      image_tag: v1.0.${{github.run_number}}-${{github.sha}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Απαραίτητο για να συγκρίνει το git ιστορικό

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install kfp python-dotenv

      - name: Detect and Submit Changed Pipelines
        env:
          IMAGE_URL: ${{ needs.build_and_push.outputs.image_url }}
          KUBEFLOW_URL: ${{ secrets.KUBEFLOW_URL }}
          PRE_COMMIT_SHA: ${{github.event.before}}
          SHA: ${{github.sha}}
          KUBEFLOW_USERNAME: ${{ secrets.KUBEFLOW_USERNAME }}
          KUBEFLOW_PASSWORD: ${{ secrets.KUBEFLOW_PASSWORD }}
        run: |
          chmod +x scripts/deploy_pipeline.sh
          ./scripts/deploy_pipeline.sh